module.exports = {
    lang: 'pt',
    get: (line, vars = []) => {
        switch(line){
            case 'mentionHelp': return `Use \`${vars[0]}help\` para ver todos os meus comandos!`;
            case 'noArgs': return `Você não forneceu nenhum argumento, ${vars[0]}!\nO uso correto seria:\n${vars[3].map(e => `\`${vars[1]}${vars[2]} ${e}\``).join('\n')}`;
            case 'cooldown': return `Por favor espere mais ${vars[0]} segundo(s) antes de usar o comando \`${vars[1]}\` novamente`;
            case 'error': return `Houve um erro ao tentar executar o comando \`${vars[0]}\`!`;
            case 'helpDescription': return 'Lista todos os comandos ou mostra informações sobre um específico';
            case 'helpUsage': return '[(comando)]';
            case 'pingDescription': return 'Ping!';
            case 'pruneDescription': return 'Deleta uma quantidade escolhida de mensagens';
            case 'pruneUsage': return '(quantidade)';
            case 'botEmbed': return 'Eu preciso de permissão para enviar links nesse canal';
            case 'botManageMessages': return 'Eu preciso de permissão para gerenciar mensagens nesse canal';
            case 'helpEmbedTitle': return 'Ajuda de comandos';
            case 'helpEmbedDescription': return `[**Servidor de suporte**](https://discord.gg/${vars[0]})\n[**Me convide**](${vars[1]})\nUse \`${vars[2]}help (comando)\` para mais informações sobre um comando específico\n\n__Note que:__\n- \`(canal)\` = \`<(menção de canal)/(ID de canal)>\`\n- \`(usuário)\` = \`<(menção de usuário)/(ID de usuário)>\`\n- \`(cargo)\` = \`<(menção de cargo)/(ID de cargo)/(nome de cargo)>\`\n- \`(emoji)\` = \`<(emoji)/(nome de emoji personalizado)/(ID de emoji personalizado)>\``;
            case 'helpEmbedFooter': return `${vars[0]} comandos | [] = Opcional - () = Variável - </> = Qualquer`;
            case 'category0': return 'Comandos';
            case 'invalidCommand': return 'Esse não é um comando válido';
            case 'helpCommandEmbedTitle': return `Ajuda para o comando ${vars[0]}`;
            case 'helpCommandEmbedFooter': return '[] = Opcional - () = Variável - </> = Qualquer';
            case 'syntax': return 'Sintaxe';
            case 'example': return 'Exemplo';
            case 'aliases': return 'Apelidos';
            case 'permissionLevel': return 'Nível de permissão';
            case 'helpCommandCooldown': return `${vars[0]} segundo(s)`;
            case 'terrible': return 'Terrível';
            case 'bad': return 'Ruim';
            case 'normal': return 'Normal';
            case 'good': return 'Bom';
            case 'average': return 'Médio';
            case 'current': return 'Atual';
            case 'invalidValue': return `Valor inválido. ${vars[0]}`;
            case 'maintenance': return 'Em manutenção, tente novamente mais tarde';
            case 'guildOnly': return 'Esse comando funciona apenas em servidores';
            case 'forbidden': return 'Você não tem permissão para usar esse comando';
            case 'disabled': return 'Esse comando foi desativado nesse canal';
            case 'permDescription': return 'Permite ou proibe cargos de usarem comandos específicos';
            case 'permUsage0': return '<allow/deny/default> <(menção de cargo)/(ID de cargo)/"(nome de cargo)"> (lista de comandos)';
            case 'permUsage1': return 'view <(menção de cargo)/(ID de cargo)/"(nome de cargo)">';
            case 'ADMINISTRATOR': return 'Administrador';
            case 'MANAGE_ROLES': return 'Gerenciar Cargos';
            case 'BAN_MEMBERS': return 'Banir Membros';
            case 'invArgs': return `Argumentos inválidos!\nO uso correto seria:\n${vars[2].map(e => `\`${vars[0]}${vars[1]} ${e}\``).join('\n')}`;
            case 'permSuccess': return `**${vars[0]}** foi ${(vars[1] === 'allow') ? 'permitido a' : 'proibido de'} usar esses comandos`;
            case 'noSpecialPerms': return 'Não há nenhuma permissão especial definida para esse cargo';
            case 'defaultPermsSuccess': return `Permissões especiais de **${vars[0]}** sobre esses comandos foram removidas`;
            case 'permsEmbedAuthor': return 'Permissões especiais';
            case 'permsAllowed': return 'Comandos permitidos';
            case 'permsDenied': return 'Comandos proibidos';
            case 'disableDescription': return 'Bloqueia comandos em canais específicos';
            case 'disableUsage0': return '(canal) <on/off> <(lista de comandos)/all>';
            case 'disableUsage1': return '(canal) view';
            case 'disableAll': return `Todos os comandos foram ${(vars[0] === 'on') ? 'bloqueados' : 'desbloqueados'} em ${vars[1]}`;
            case 'disableSome': return `Esses comandos foram ${(vars[0] === 'on') ? 'bloqueados' : 'desbloqueados'} em ${vars[1]}`;
            case 'permsEmbedDesc': return `Cargo: ${vars[0]}`;
            case 'noDisabledCmds': return 'Não há comandos bloqueados nesse canal';
            case 'disabledEmbedAuthor': return 'Comandos de canais específicos';
            case 'disabledEmbedDesc': return `Canal: ${vars[0]}`;
            case 'disabledField': return 'Bloqueado';
            case 'achieveGuild': return `Parabéns ${vars[0]}! Você conquistou o cargo **${vars[1]}**`;
            case 'achieveDM': return `Parabéns! Você conquistou o cargo **${vars[0]}** no servidor **${vars[1]}**`;
            case 'msgexpDescription': return 'Gerencia o sistema de xp desse servidor';
            case 'msgexpUsage0': return '<enable/stack> <on/off>';
            case 'msgexpUsage1': return 'roles set (cargo) (xp)';
            case 'msgexpUsage2': return 'roles remove <(cargo)/all>';
            case 'msgexpUsage3': return 'user <add/remove/set> (xp) (lista de usuários)';
            case 'msgexpUsage4': return 'ignore role <add/remove> (cargo)';
            case 'msgexpUsage5': return 'ignore channel <add/remove> (canal)';
            case 'msgexpUsage6': return 'notify <default/none/dm/(canal)>';
            case 'msgexpUsage7': return '<view/reset>';
            case 'xpEnable': return `Sistema de xp do servidor ${(vars[0] === 'on') ? 'ativado': 'desativado'}`
            case 'xpStack': return `Acumulo de cargos de xp ${(vars[0] === 'on') ? 'ativado': 'desativao'}`
            case 'manageRole': return 'Eu preciso de permissão para gerenciar esse cargo';
            case 'sameXp': return 'Já existe outro cargo definido para essa quantidade de xp';
            case 'maxXpRoles': return 'O número máximo de cargos de xp é 20';
            case 'setXpRole': return `**${vars[0]}** definido como recompensa para **${vars[1]}** xp\nesteja ciente que membros apenas receberão esse cargo ao enviar novas mensagens`;
            case 'resetXpRoles': return `Todos os cargos de xp foram removidos\nesteja ciente que esses cargos não serão removidos automaticamente dos membros, se você quiser isso, é recomendado deletar os cargos do servidor para que nenhum membro continue com eles`;
            case 'removeXpRole': return `**${vars[0]}** foi removido das recompensas de xp\nesteja ciente que esse cargo não será removido automaticamente dos membros, se você quiser isso, é recomendado deletar o cargo do servidor para que nenhum membro continue com ele`;
            case 'setUserXp': return 'Novas quantias de xp definidas';
            case 'xpIgnoreRole': return `O cargo **${vars[0]}** ${(vars[1] === 'add') ? 'não vai' : 'vai'} receber xp`;
            case 'xpIgnoreChannel': return `Usuários ${(vars[0] === 'add') ? 'não vão' : 'vão'} receber xp em ${vars[1]}`;
            case 'notifyDefault': return `Notificações de novos cargos de xp serão enviadas ${(vars[0] === 'dm') ? 'nas MDs' : 'no canal onde o cargo foi alcançado'}`;
            case 'notifyNone': return 'Nenhuma notificação de novos cargos de xp será enviada';
            case 'notifyChannel': return `Notificações de novos cargos serão enviadas em ${vars[0]}`;
            case 'notifyDefaultView': return '\`Mesmo canal\`';
            case 'notifyDMView': return '\`MDs\`';
            case 'notifyNoneView': return '\`Nenhum\`';
            case 'xpViewEmbedAuthor': return 'Configurações do sistema de xp do servidor';
            case 'xpViewEmbedDesc': return `Ativado: \`${vars[0] ? 'sim': 'não'}\`\nAcumulo: \`${vars[1] ? 'não': 'sim'}\`\nNotificações: ${vars[2]}`;
            case 'xpViewRoles': return 'Cargos conquistáveis';
            case 'xpViewIgnoredRoles': return 'Cargos ignorados';
            case 'xpViewIgnoredChannels': return 'Canais ignorados';
            case 'resetXpConfirm': return 'Isso **__REDEFINIRÁ O XP DE TODOS OS USUÁRIOS__** para 0, você tem certeza que deseja prosseguir?';
            case 'timedOut': return 'Limite de tempo da operação atingido';
            case 'cancelled': return 'Operação cancelada';
            case 'resetXp': return 'O xp do servidor foi redefinido com sucesso';
            case 'memberManageRole': return 'Você não tem permissão para gerenciar esse cargo';
            case 'sendMessages': return 'Eu preciso de permissão para enviar mensagens nesse canal';
            case 'rolemenuDescription': return 'Cria uma mensagem onde usuários podem reagir para reivindicar um ou mais cargos';
            case 'rolemenuUsage0': return 'create (canal) <(menção de cargo)/(ID de cargo)/"(nome de cargo)"> (emoji) [(lista de cargos e emojis)] [toggle]';
            case 'rolemenuUsage1': return 'edit (ID de menu) <(menção de cargo)/(ID de cargo)/"(nome de cargo)"> (emoji) [(lista de cargos e emojis)] [toggle]';
            case 'maxRolesMenu': return 'O número máximo de cargos por menu é 40';
            case 'botReactions': return 'Eu preciso de permissão para adicionar reações nesse canal';
            case 'maxRolemenus': return 'O número máximo de menus por servidor é 20';
            case 'uniqueEmoji': return 'Cada emoji só pode ser usado uma vez por menu';
            case 'loading': return 'Carregando...';
            case 'rolemenuEmbedAuthor': return 'Reaja para reivindicar um cargo';
            case 'rolemenuCreated': return 'Rolemenu criada com sucesso';
            case 'menu404': return 'Menu não encotrado';
            case 'rolemenuEdited': return 'Rolemenu editado com sucesso';
            case 'configsDescription': return 'Configurações gerais do servidor';
            case 'configsUsage0': return 'prefix (novo prefixo)';
            case 'configsUsage1': return 'language <en/pt>';
            case 'configsUsage2': return 'view';
            case 'longPrefix': return 'O prefixo não pode conter mais de 10 caracteres';
            case 'newPrefix': return 'Prefixo do servidor atualizado';
            case 'lang404': return 'Idioma não suportado';
            case 'newLang': return 'Idioma do servidor atualizado';
            case 'configsEmbedAuthor': return 'Configurações do servidor';
            case 'configsEmbedDesc': return `Prefixo: \`${vars[0]}\`\nIdioma: \`${vars[1]}\`\nRegistrar anexos: \`${vars[2] ? 'ativado' : 'desativado'}\`\nCanal de registro de warn: ${vars[3].warn ? `<#${vars[3].warn}>` : '`nenhum`'}\nCanal de registro de mute: ${vars[3].mute ? `<#${vars[3].mute}>` : '`nenhum`'}\nCanal de registro de kick: ${vars[3].kick ? `<#${vars[3].kick}>` : '`nenhum`'}\nCanal de registro de ban: ${vars[3].ban ? `<#${vars[3].ban}>` : '`nenhum`'}\nNúmero de dias de mensagens deletadas em bans: \`${vars[4]}\`\nCargo de mute: ${vars[5] ? `<@&${vars[5]}>` : '`nenhum`'}`;
            case 'betaCommand': return 'Esse comando atualmente está disponível apenas para servidor que ativaram funcionalidade beta nas configurações do bot';
            case 'premiumCommand': return `Esse comando é uma funcionalidade premium, use \`${vars[0]}premium\` para mais informações sobre se tornar premium`;
            case 'botWebhooks': return 'Eu preciso de permissão para gerenciar webhooks nesse canal';
            case 'executor': return `\nExecutor: ${vars[0]}`;
            case 'delmsgEmbedFooter': return `${vars[0]} | Mensagem original enviada as:`;
            case 'delmsgEmbedAuthor': return 'Mensagem deletada';
            case 'delmsgEmbedDesc': return `Autor: ${vars[0]}\nCanal: ${vars[1]}${vars[2]}`;
            case 'delmsgEmbedContent': return 'Conteúdo';
            case 'delmsgEmbedAttachmentsTitle': return 'Anexos';
            case 'delmsgEmbedAttachmentsMedia': return `**[Anexo-${vars[0]}-Mídia](${vars[1]})**`;
            case 'delmsgEmbedAttachmentsFile': return `**[Anexo-${vars[0]}-Arquivo](${vars[1]})**`;
            case 'actionlogsDescription': return 'Gerencia registros de ações no servidor';
            case 'actionlogsUsage0': return 'defaultchannel (canal)';
            case 'actionlogsUsage1': return 'set delmsg <(canal)/default>';
            case 'actionlogsUsage2': return 'ignore channel <add/remove> (canal) <delmsg/all>';
            case 'actionlogsUsage3': return 'ignore channel view (canal)';
            case 'actionlogsUsage4': return 'ignore role <add/remove> (cargo) <delmsg/all/view>';
            case 'actionlogsUsage5': return 'ignore role view (cargo)';
            case 'newDefaultHookReason': return 'Webhook do canal de registros padrão';
            case 'oldDefaultHookReason': return 'Webhook do canal antigo de registros padrão';
            case 'newDefaultLog': return `Canal de registros padrão definido para ${vars[0]}`;
            case 'noDefaultLog': return 'Canal de registros padrão não definido';
            case 'oldHookReason': return `Webhook do canal antigo de registros de ${vars[0]}`;
            case 'newDefaultLogSuccess': return 'Essa ação foi definida para ser registrada no canal de registros padrão';
            case 'newHookReason': return `Webhook do canal de registros de ${vars[0]}`;
            case 'newLogSuccess': return `Essa ação foi definida para ser registrada em ${vars[0]}`;
            case 'removeLogSuccess': return 'Essa ação não será registrada';
            case 'noIgnoredActionsChannel': return 'Nenhum ação está sendo ignorada nesse canal'
            case 'ignoredActionsChannelEmbedAuthor': return 'Canal ignorado';
            case 'ignoredActionsChannelEmbedDesc': return `Canal: ${vars[0]}`;
            case 'ignoredActionsEmbedFooter': return `${vars[0]} ações ignoradas`;
            case 'ignoredActionsEmbedActionsTitle': return 'Ações';
            case 'actiondelmsg': return '**mensagens deletadas**';
            case 'noIgnoredActionsRole': return 'Nenhuma ação está sendo ignorada para esse cargo';
            case 'ignoredActionsRoleEmbedAuthor': return 'Cargo ignorado';
            case 'ignoredActionsRoleEmbedDesc': return `Cargo: ${vars[0]}`;
            case 'allActionsIgnoredChannelSuccess': return `Todas as ações serão ignoradas em ${vars[0]}`;
            case 'noActionsIgnoredChannelSuccess': return `Nenhuma ação será ignorada em ${vars[0]}`;
            case 'allActionsIgnoredRoleSuccess': return `Todas as ações serão ignorada para **${vars[0]}**`;
            case 'noActionsIgnoredRoleSuccess': return `Nenhuma ação será ignorada para **${vars[0]}**`;
            case 'actionIgnoredChannelSuccess': return `**${vars[0]}** será ignorada em ${vars[1]}`;
            case 'actionNotIgnoredChannelSuccess': return `**${vars[0]}** não será ignorada em ${vars[1]}`;
            case 'actionIgnoredRoleSuccess': return `**${vars[0]}** será ignorada para **${vars[1]}**`;
            case 'actionNotIgnoredRoleSuccess': return `**${vars[0]}** não será ignorada para **${vars[1]}**`;
            case 'logsViewEmbedAuthor': return 'Informações sobre registro de ações';
            case 'logsViewEmbedDesc': return `Canal padrão: ${vars[0] ? `<#${vars[0].channelID}>` : '\`nenhum\`'}`;
            case 'logsViewEmbedActionsTitle': return 'Ações registradas';
            case 'logsViewEmbedActions': return `**${vars[0]}** - ${vars[1] ? `<#${vars[1]}>` : '`Padrão`'}`
            case 'logsViewEmbedIgnoredChannelsTitle': return 'Canais ignorados';
            case 'logsViewEmbedIgnoredRolesTitle': return 'Cargos ignorados';
            case 'logsViewEmbedIgnoredSome': return 'Alguns';
            case 'logsViewEmbedIgnoredAll': return 'Todos';
            case 'logattachmentsBadArgs': return 'Essa configuração deve ser definida como `on` ou `off`';
            case 'logattachmentsNoHook': return 'Escolha um canal para registrar mensagens deletadas primeiro';
            case 'logattachmentsNoNSFW': return 'Para usar essa configuração o canal de registros de mensagens deletadas precisa estar definido como NSFW';
            case 'logattachmentsOnSuccess': return 'Anexos serão registrados';
            case 'logattachmentsOffSuccess': return 'Anexos não serão registrados';
            case 'premiumDescription': return 'Informações sobre se tornar premium';
            case 'alreadyPremium': return 'Esse servidor já tem acesso a funções premium';
            case 'premiumEmbedDesc': return `Ainda não é possível comprar o modo premium, se você deseja solicitar parceria ou pagar pelo premium diretamente [**entre no servidor de suporte**](https://discord.gg/${vars[0]}) e contate os desenvolvedores`;
        }
    },
};